---

- name: Stop the firewall on RedHat
  service: name=firewalld state=stopped enabled=false
  when: ansible_os_family== "RedHat"


- name: Stop the firewall on Ubuntu
  service: name=ufw state=stopped enabled=false
  when: ansible_os_family== "Debian"
