---
- hosts: "{{ host_ip}}"
   #gather_facts: false
  tasks:
    - name: create user
      win_user:
        name: "{{ name }}"
        password: "{{ password }}"
        state: present
        groups:
          - "{{ group }}"
