---
- hosts: "{{ host_ip}}"
   #gather_facts: false
  tasks:
    - name: create user
      win_user:
        name: "{{ name }}"
        password: "{{ password }}"
        state: present
        update_password: on_create
        groups:
          - {{ group }}
