- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Provision an instance
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: "{{ key_name }}"
         instance_type: "{{ instance_type }}"
         instance_profile_name: "{{ instance_profile_name }}"
         image: "{{ image }}"
         wait: yes
         wait_timeout: 500
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         group_id: "{{ group_id }}"
         assign_public_ip: yes
         count: 1
         count_tag: "{{ count_tag }}"
         instance_tags: 
            Name: "{{ instance_tags }}"
         region: "{{ region }}"
         user_data: "{{ lookup('template', 'userdata.txt.j2') }}"
      register: ec2
    - name: wait for WinRM to answer on all hosts
      wait_for:
        port: 5985
        host: "{{ item.private_ip }}"
        timeout: 600
      with_items: "{{ ec2.instances }}"   
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: windows
      with_items: "{{ ec2.instances }}"
    - name: Pause the script
      pause:
        minutes: 5
- name: Post tasks
  hosts: windows
  gather_facts: True
  tasks: 
  - name: Create an user
    win_user:
      name: "{{ username }}"
      password: "{{ password }}"
      state: present
      groups:
        - "{{ windows_group }}"
  - name: Adding to domain
    win_domain_membership:
      dns_domain_name: "{{ domain_name }}"
      domain_admin_user: "{{ domain_user }}"
      domain_admin_password: "{{ domain_password }}"
      state: domain
    register: domain_state
  - name: Reboot vm
    win_reboot:
    when: domain_state.reboot_required
