---
- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Provision an instance
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: "{{ key_name }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: yes
         wait_timeout: 500
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         group_id: "{{ group_id }}"
         assign_public_ip: yes
         count: 1
         count_tag:  "{{ count_tag }}"
         instance_tags: 
            Name: "{{ instance_tags }}"
         region: "{{ region }}"
      register: ec2
   
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Post tasks 
  hosts: launched
  become: True
  gather_facts: True
  tasks:
  - name: Create file
    file: path=/tmp/file.txt state=touch
  - name: Create user
    user: name= "{{ username }}" state=present
