---
- name: Create VMware guest
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Deploy guest from template
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ useername }}"
      password: "{{ password }}"
      validate_certs: false
      datacenter: "{{ datacenter }}"
      state: poweredon
      name: "{{ name }}"
      template: "{{ template}}"
      disk:
       - size_gb: "{{ size_gb }}"
         datastore: "{{ datastore }}"
         type: "{{ type }}"
         autoselect_datastore: yes
      hardware:
        memory_mb: "{{ memory_mb }}"
        num_cpus: "{{ num_cpus }}"
      #networks:
       #- name: "{{ network_name }}"
         #device_type: "{{ device_type }}"
      customization:
         autologon: yes
         hostname: "{{ vm_hostname }}"
    delegate_to: localhost
